<?php

namespace Database\Seeders;

use App\Models\BillingStatus;
use App\Models\Setting;
use App\Models\TranslationKey;
use App\Models\User;
use App\Models\Venue;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CoreSeeder extends Seeder
{
    /**
     * Bump this number when seed data changes in a release.
     * Existing deployments with a lower version will re-run the seeder.
     * Set env CORE_SEED_FRESH=true to force re-seed regardless of version.
     */
    private const SEED_VERSION = 6;

    public function run(): void
    {
        // Skip if already seeded at or above current version.
        // Allow forcing via --force flag or CORE_SEED_FRESH env variable.
        $forceFresh = (bool) env('CORE_SEED_FRESH', false);
        $currentVersion = (int) Setting::getValue('core_seed_version', 0);

        if (! $forceFresh && $currentVersion >= self::SEED_VERSION) {
            $this->command?->info("CoreSeeder: already seeded (version {$currentVersion}). Skipping.");

            return;
        }

        $this->command?->info("CoreSeeder: running (current version: {$currentVersion}, target: ".self::SEED_VERSION.')...');
        // ---- Users ----
        $admin = User::firstOrCreate(
            ['username' => 'admin'],
            [
                'name' => 'System Admin',
                'email' => 'admin@serveo.local',
                'password' => Hash::make('password'),
                'preferred_language_code' => 'pt-PT',
                'is_active' => true,
            ]
        );
        $admin->syncRoles(['ADMIN']);

        // ---- Venue ----
        $venue = Venue::updateOrCreate(
            ['venue_code' => 'MAIN'],
            ['name' => 'Salão Principal', 'is_active' => true]
        );

        // ---- Billing statuses ----
        // MVP starts with only ACTIVE and CLOSED. Admin may add more later via panel.
        foreach ([
            ['ACTIVE', 'Ativo',   10],
            ['CLOSED', 'Fechado', 20],
        ] as [$code, $name, $sort]) {
            BillingStatus::firstOrCreate(
                ['code' => $code],
                ['display_name' => $name, 'sort_order' => $sort, 'is_active' => true]
            );
        }

        // ---- Translations (complete operational UI set) ----
        $translations = [
            // ---------- app ----------
            ['pt-PT', 'app', 'name', 'Serveo'],
            ['pt-PT', 'app', 'cancel', 'Cancelar'],
            ['pt-PT', 'app', 'back', 'Voltar'],
            ['pt-PT', 'app', 'save', 'Guardar'],
            ['pt-PT', 'app', 'delete', 'Eliminar'],
            ['pt-PT', 'app', 'edit', 'Editar'],
            ['pt-PT', 'app', 'create', 'Criar'],
            ['pt-PT', 'app', 'search', 'Pesquisar'],
            ['pt-PT', 'app', 'actions', 'Ações'],
            ['pt-PT', 'app', 'status', 'Estado'],
            ['pt-PT', 'app', 'total', 'Total'],
            ['pt-PT', 'app', 'balance', 'Saldo'],
            ['pt-PT', 'app', 'notes', 'Notas'],
            ['pt-PT', 'app', 'yes', 'Sim'],
            ['pt-PT', 'app', 'no', 'Não'],
            ['pt-PT', 'app', 'open', 'Aberto'],
            ['pt-PT', 'app', 'closed', 'Fechado'],
            ['pt-PT', 'app', 'waiting', 'À espera'],
            ['pt-PT', 'app', 'active', 'Ativo'],
            ['pt-PT', 'app', 'empty', 'Vazio'],
            ['pt-PT', 'app', 'none', 'Nenhum'],
            ['pt-PT', 'app', 'error', 'Erro'],
            ['pt-PT', 'app', 'success', 'Sucesso'],
            ['pt-PT', 'app', 'warning', 'Aviso'],
            ['pt-PT', 'app', 'cover_count', 'N.º de pessoas'],
            ['pt-PT', 'app', 'delivery_label_example', 'ex: Centro'],
            ['pt-PT', 'app', 'select', 'Selecionar'],
            ['pt-PT', 'app', 'pairs', 'Lugares'],
            ['pt-PT', 'app', 'pair', 'Lugar'],
            ['pt-PT', 'app', 'covers', 'Pessoas'],
            ['pt-PT', 'app', 'charges', 'Consumo'],
            ['pt-PT', 'app', 'venue', 'Espaço'],
            ['pt-PT', 'app', 'category', 'Categoria'],
            ['pt-PT', 'app', 'route', 'Rota'],
            ['pt-PT', 'app', 'health', 'Saúde'],
            ['pt-PT', 'app', 'printer', 'Impressora'],
            ['pt-PT', 'app', 'attempts', 'Tentativas'],
            ['pt-PT', 'app', 'created', 'Criado'],
            ['pt-PT', 'app', 'completed', 'Concluído'],
            ['pt-PT', 'app', 'retry', 'Reenviar'],
            ['pt-PT', 'app', 'cancel_action', 'Cancelar'],
            ['pt-PT', 'app', 'download', 'Descarregar'],
            ['pt-PT', 'app', 'user', 'Utilizador'],
            ['pt-PT', 'app', 'roles', 'Funções'],
            ['pt-PT', 'app', 'last_login', 'Último login'],
            ['pt-PT', 'app', 'rows', 'Linhas'],
            ['pt-PT', 'app', 'seats', 'Lugares'],
            ['pt-PT', 'app', 'requested_by', 'Solicitado por'],
            ['pt-PT', 'app', 'type', 'Tipo'],
            ['pt-PT', 'app', 'format', 'Formato'],
            ['pt-PT', 'app', 'start', 'Início'],
            ['pt-PT', 'app', 'end', 'Fim'],
            ['pt-PT', 'app', 'range_start', 'Início do intervalo'],
            ['pt-PT', 'app', 'range_end', 'Fim do intervalo'],
            ['pt-PT', 'app', 'service_session', 'Sessão de serviço'],
            ['pt-PT', 'app', 'address_ip_hostname', 'Endereço IP / hostname'],
            ['pt-PT', 'app', 'agent_url', 'URL do agente'],
            ['pt-PT', 'app', 'agent_internal_id', 'ID interno no agente'],
            ['pt-PT', 'app', 'last_seen', 'Visto pela última vez'],
            ['pt-PT', 'app', 'room', 'Sala'],
            ['pt-PT', 'app', 'location', 'Localização'],
            ['pt-PT', 'app', 'navigation_group_operation', 'Operação'],
            ['pt-PT', 'app', 'navigation_group_config', 'Configuração'],
            ['pt-PT', 'app', 'navigation_label_accounting_exports', 'Exportações contabilísticas'],
            ['pt-PT', 'app', 'model_label_accounting_export', 'Exportação'],
            ['pt-PT', 'app', 'navigation_label_printer_routes', 'Rotas de impressão'],
            ['pt-PT', 'app', 'navigation_label_fulfillment_routes', 'Rotas de produção'],
            ['pt-PT', 'app', 'navigation_label_print_jobs', 'Fila de impressão'],
            ['pt-PT', 'app', 'navigation_label_service_sessions', 'Sessões de serviço'],
            ['pt-PT', 'app', 'printer_type_generic', 'Genérica'],
            ['pt-PT', 'app', 'connection_type_lan', 'LAN direta (ESC/POS porta 9100)'],
            ['pt-PT', 'app', 'connection_type_usb_agent', 'USB através do agente local'],
            ['pt-PT', 'app', 'connection_type_null', 'Simulada (escreve no disco)'],
            ['pt-PT', 'app', 'job_kind_production_ticket', 'Ticket de produção'],
            ['pt-PT', 'app', 'job_kind_bill', 'Conta'],
            ['pt-PT', 'app', 'document_type_production_ticket', 'Ticket de produção'],
            ['pt-PT', 'app', 'document_type_void_slip', 'Anulação'],
            ['pt-PT', 'app', 'helper_text_production_only', 'Aplica-se apenas a tickets de produção e anulações'],
            ['pt-PT', 'app', 'session_type_lunch', 'Almoço'],
            ['pt-PT', 'app', 'language_pt', 'Português (PT)'],
            ['pt-PT', 'app', 'language_en', 'English (US)'],
            ['pt-PT', 'app', 'helper_text_session_label', 'Único por venue. Ex.: "2026-04-29 DINNER"'],
            ['pt-PT', 'app', 'navigation_group_audit', 'Auditoria'],
            ['pt-PT', 'app', 'navigation_label_billing_status', 'Estados de grupo'],
            ['pt-PT', 'app', 'navigation_label_menu_categories', 'Categorias de menu'],
            ['pt-PT', 'app', 'navigation_label_menu_items', 'Itens de menu'],
            ['pt-PT', 'app', 'navigation_label_printers', 'Impressoras'],
            ['pt-PT', 'app', 'navigation_label_rows', 'Linhas (Rows)'],
            ['pt-PT', 'app', 'navigation_label_sections', 'Salas (Sections)'],
            ['pt-PT', 'app', 'navigation_label_audit_events', 'Eventos de auditoria'],
            ['pt-PT', 'app', 'navigation_label_users', 'Utilizadores'],
            ['pt-PT', 'app', 'model_label_user', 'Utilizador'],
            ['pt-PT', 'app', 'plural_model_label_users', 'Utilizadores'],
            ['pt-PT', 'app', 'plural_model_label_accounting_exports', 'Exportações contabilísticas'],
            ['pt-PT', 'app', 'printer_type_kitchen', 'Cozinha'],
            ['pt-PT', 'app', 'printer_type_bar', 'Bar'],
            ['pt-PT', 'app', 'printer_type_bill', 'Conta (caixa)'],
            ['pt-PT', 'app', 'document_type_bill', 'Conta'],
            ['pt-PT', 'app', 'status_pending', 'Pendente'],
            ['pt-PT', 'app', 'status_in_progress', 'Em curso'],
            ['pt-PT', 'app', 'status_printed', 'Impresso'],
            ['pt-PT', 'app', 'status_failed', 'Falhou'],
            ['pt-PT', 'app', 'status_canceled', 'Cancelado'],
            ['pt-PT', 'app', 'status_planned', 'Planeada'],
            ['pt-PT', 'app', 'status_open', 'Aberta'],
            ['pt-PT', 'app', 'status_closed', 'Fechada'],
            ['pt-PT', 'app', 'session_type_dinner', 'Jantar'],
            ['pt-PT', 'app', 'session_type_event', 'Evento'],
            ['pt-PT', 'app', 'theme', 'Tema'],
            ['pt-PT', 'app', 'language', 'Idioma'],
            ['pt-PT', 'app', 'theme_light', 'Claro'],
            ['pt-PT', 'app', 'theme_dark', 'Escuro'],
            ['pt-PT', 'app', 'theme_system', 'Sistema'],
            ['pt-PT', 'app', 'route_kitchen', 'Cozinha'],
            ['pt-PT', 'app', 'route_bar', 'Bar'],
            ['pt-PT', 'app', 'route_none', 'Sem rota'],
            ['pt-PT', 'app', 'type_session_summary', 'Resumo de sessão'],
            ['pt-PT', 'app', 'type_full_ledger', 'Livro completo'],
            ['pt-PT', 'app', 'assign_server', 'Atribuir servidor'],
            ['pt-PT', 'app', 'server', 'Servidor'],
            ['pt-PT', 'app', 'navigation_label_billing_groups', 'Contas'],
            ['pt-PT', 'app', 'model_label_billing_group', 'Conta'],
            ['pt-PT', 'app', 'plural_model_label_billing_groups', 'Contas'],
            ['pt-PT', 'app', 'code', 'Código'],
            ['pt-PT', 'app', 'session', 'Sessão'],
            ['pt-PT', 'app', 'opened_by', 'Aberto por'],
            ['pt-PT', 'app', 'zones', 'Zonas'],
            ['pt-PT', 'app', 'servers', 'Servidores'],
            ['pt-PT', 'app', 'closed', 'Fechado'],
            ['pt-PT', 'app', 'details', 'Detalhes'],
            ['pt-PT', 'app', 'opened_at', 'Aberto em'],
            ['pt-PT', 'app', 'closed_at', 'Fechado em'],
            ['pt-PT', 'app', 'range', 'Intervalo'],
            ['pt-PT', 'app', 'session_already_open', 'Já existe uma sessão aberta neste espaço de evento. Feche-a antes de abrir uma nova.'],
            ['pt-PT', 'app', 'session_has_open_groups', 'Não é possível fechar a sessão. Existem contas abertas nesta sessão. Feche-as ou reatribua-as primeiro.'],
            ['pt-PT', 'app', 'model_label_fulfillment_route', 'Rota de produção'],
            ['pt-PT', 'app', 'plural_model_label_fulfillment_routes', 'Rotas de produção'],
            ['pt-PT', 'app', 'display_name', 'Nome a exibir'],
            ['pt-PT', 'app', 'sort_order', 'Ordem'],
            ['pt-PT', 'app', 'is_active', 'Ativo'],
            ['pt-PT', 'app', 'navigation_label_document_print_configs', 'Configuração de impressão'],
            ['pt-PT', 'app', 'model_label_document_print_config', 'Configuração de impressão'],
            ['pt-PT', 'app', 'plural_model_label_document_print_configs', 'Configurações de impressão'],
            ['pt-PT', 'app', 'helper_text_group_items', 'Agrupar itens iguais e mostrar quantidade (ex: "3x Pizza"). Desligado: cada unidade numa linha própria.'],
            ['pt-PT', 'app', 'helper_text_ignore_variants', 'Não imprimir nomes de variantes (ex: "Casa", "Reserva") neste tipo de documento.'],
            ['pt-PT', 'app', 'helper_text_ignore_modifiers', 'Não imprimir nomes de modificadores (ex: "sem cebola") neste tipo de documento.'],

            ['en-US', 'app', 'name', 'Serveo'],
            ['en-US', 'app', 'cancel', 'Cancel'],
            ['en-US', 'app', 'back', 'Back'],
            ['en-US', 'app', 'save', 'Save'],
            ['en-US', 'app', 'delete', 'Delete'],
            ['en-US', 'app', 'edit', 'Edit'],
            ['en-US', 'app', 'create', 'Create'],
            ['en-US', 'app', 'search', 'Search'],
            ['en-US', 'app', 'actions', 'Actions'],
            ['en-US', 'app', 'status', 'Status'],
            ['en-US', 'app', 'total', 'Total'],
            ['en-US', 'app', 'balance', 'Balance'],
            ['en-US', 'app', 'notes', 'Notes'],
            ['en-US', 'app', 'yes', 'Yes'],
            ['en-US', 'app', 'no', 'No'],
            ['en-US', 'app', 'open', 'Open'],
            ['en-US', 'app', 'closed', 'Closed'],
            ['en-US', 'app', 'waiting', 'Waiting'],
            ['en-US', 'app', 'active', 'Active'],
            ['en-US', 'app', 'empty', 'Empty'],
            ['en-US', 'app', 'none', 'None'],
            ['en-US', 'app', 'error', 'Error'],
            ['en-US', 'app', 'success', 'Success'],
            ['en-US', 'app', 'warning', 'Warning'],
            ['en-US', 'app', 'cover_count', 'Cover Count'],
            ['en-US', 'app', 'delivery_label_example', 'e.g. Center'],
            ['en-US', 'app', 'select', 'Select'],
            ['en-US', 'app', 'pairs', 'Pairs'],
            ['en-US', 'app', 'pair', 'Pair'],
            ['en-US', 'app', 'covers', 'Covers'],
            ['en-US', 'app', 'charges', 'Charges'],
            ['en-US', 'app', 'venue', 'Venue'],
            ['en-US', 'app', 'category', 'Category'],
            ['en-US', 'app', 'route', 'Route'],
            ['en-US', 'app', 'health', 'Health'],
            ['en-US', 'app', 'printer', 'Printer'],
            ['en-US', 'app', 'attempts', 'Attempts'],
            ['en-US', 'app', 'created', 'Created'],
            ['en-US', 'app', 'completed', 'Completed'],
            ['en-US', 'app', 'retry', 'Retry'],
            ['en-US', 'app', 'cancel_action', 'Cancel'],
            ['en-US', 'app', 'download', 'Download'],
            ['en-US', 'app', 'user', 'User'],
            ['en-US', 'app', 'roles', 'Roles'],
            ['en-US', 'app', 'last_login', 'Last Login'],
            ['en-US', 'app', 'rows', 'Rows'],
            ['en-US', 'app', 'seats', 'Seats'],
            ['en-US', 'app', 'requested_by', 'Requested by'],
            ['en-US', 'app', 'type', 'Type'],
            ['en-US', 'app', 'format', 'Format'],
            ['en-US', 'app', 'start', 'Start'],
            ['en-US', 'app', 'end', 'End'],
            ['en-US', 'app', 'range_start', 'Range Start'],
            ['en-US', 'app', 'range_end', 'Range End'],
            ['en-US', 'app', 'service_session', 'Service Session'],
            ['en-US', 'app', 'address_ip_hostname', 'IP Address / hostname'],
            ['en-US', 'app', 'agent_url', 'Agent URL'],
            ['en-US', 'app', 'agent_internal_id', 'Internal agent ID'],
            ['en-US', 'app', 'last_seen', 'Last seen'],
            ['en-US', 'app', 'room', 'Room'],
            ['en-US', 'app', 'location', 'Location'],
            ['en-US', 'app', 'navigation_group_operation', 'Operation'],
            ['en-US', 'app', 'navigation_group_config', 'Configuration'],
            ['en-US', 'app', 'navigation_label_accounting_exports', 'Accounting Exports'],
            ['en-US', 'app', 'model_label_accounting_export', 'Export'],
            ['en-US', 'app', 'navigation_label_printer_routes', 'Printer Routes'],
            ['en-US', 'app', 'navigation_label_fulfillment_routes', 'Fulfillment Routes'],
            ['en-US', 'app', 'model_label_fulfillment_route', 'Fulfillment Route'],
            ['en-US', 'app', 'plural_model_label_fulfillment_routes', 'Fulfillment Routes'],
            ['en-US', 'app', 'navigation_label_print_jobs', 'Print Queue'],
            ['en-US', 'app', 'navigation_label_service_sessions', 'Service Sessions'],
            ['en-US', 'app', 'printer_type_generic', 'Generic'],
            ['en-US', 'app', 'connection_type_lan', 'LAN direct (ESC/POS port 9100)'],
            ['en-US', 'app', 'connection_type_usb_agent', 'USB via local agent'],
            ['en-US', 'app', 'connection_type_null', 'Simulated (writes to disk)'],
            ['en-US', 'app', 'job_kind_production_ticket', 'Production Ticket'],
            ['en-US', 'app', 'job_kind_bill', 'Bill'],
            ['en-US', 'app', 'document_type_production_ticket', 'Production Ticket'],
            ['en-US', 'app', 'document_type_void_slip', 'Void Slip'],
            ['en-US', 'app', 'helper_text_production_only', 'Applies only to production tickets and void slips'],
            ['en-US', 'app', 'session_type_lunch', 'Lunch'],
            ['en-US', 'app', 'language_pt', 'Portuguese (PT)'],
            ['en-US', 'app', 'language_en', 'English (US)'],
            ['en-US', 'app', 'helper_text_session_label', 'Unique per venue. E.g.: "2026-04-29 DINNER"'],
            ['en-US', 'app', 'navigation_group_audit', 'Audit'],
            ['en-US', 'app', 'navigation_label_billing_status', 'Group Statuses'],
            ['en-US', 'app', 'navigation_label_menu_categories', 'Menu Categories'],
            ['en-US', 'app', 'navigation_label_menu_items', 'Menu Items'],
            ['en-US', 'app', 'navigation_label_printers', 'Printers'],
            ['en-US', 'app', 'navigation_label_rows', 'Rows'],
            ['en-US', 'app', 'navigation_label_sections', 'Sections'],
            ['en-US', 'app', 'navigation_label_audit_events', 'Audit Events'],
            ['en-US', 'app', 'navigation_label_users', 'Users'],
            ['en-US', 'app', 'model_label_user', 'User'],
            ['en-US', 'app', 'plural_model_label_users', 'Users'],
            ['en-US', 'app', 'plural_model_label_accounting_exports', 'Accounting Exports'],
            ['en-US', 'app', 'printer_type_kitchen', 'Kitchen'],
            ['en-US', 'app', 'printer_type_bar', 'Bar'],
            ['en-US', 'app', 'printer_type_bill', 'Bill (cashier)'],
            ['en-US', 'app', 'document_type_bill', 'Bill'],
            ['en-US', 'app', 'status_pending', 'Pending'],
            ['en-US', 'app', 'status_in_progress', 'In Progress'],
            ['en-US', 'app', 'status_printed', 'Printed'],
            ['en-US', 'app', 'status_failed', 'Failed'],
            ['en-US', 'app', 'status_canceled', 'Canceled'],
            ['en-US', 'app', 'status_planned', 'Planned'],
            ['en-US', 'app', 'status_open', 'Open'],
            ['en-US', 'app', 'status_closed', 'Closed'],
            ['en-US', 'app', 'session_type_dinner', 'Dinner'],
            ['en-US', 'app', 'session_type_event', 'Event'],
            ['en-US', 'app', 'theme', 'Theme'],
            ['en-US', 'app', 'language', 'Language'],
            ['en-US', 'app', 'theme_light', 'Light'],
            ['en-US', 'app', 'theme_dark', 'Dark'],
            ['en-US', 'app', 'theme_system', 'System'],
            ['en-US', 'app', 'route_kitchen', 'Kitchen'],
            ['en-US', 'app', 'route_bar', 'Bar'],
            ['en-US', 'app', 'route_none', 'No route'],
            ['en-US', 'app', 'type_session_summary', 'Session Summary'],
            ['en-US', 'app', 'type_full_ledger', 'Full Ledger'],
            ['en-US', 'app', 'assign_server', 'Assign Server'],
            ['en-US', 'app', 'server', 'Server'],
            ['en-US', 'app', 'navigation_label_billing_groups', 'Billing Groups'],
            ['en-US', 'app', 'model_label_billing_group', 'Billing Group'],
            ['en-US', 'app', 'plural_model_label_billing_groups', 'Billing Groups'],
            ['en-US', 'app', 'code', 'Code'],
            ['en-US', 'app', 'session', 'Session'],
            ['en-US', 'app', 'opened_by', 'Opened by'],
            ['en-US', 'app', 'zones', 'Zones'],
            ['en-US', 'app', 'servers', 'Servers'],
            ['en-US', 'app', 'closed', 'Closed'],
            ['en-US', 'app', 'details', 'Details'],
            ['en-US', 'app', 'opened_at', 'Opened at'],
            ['en-US', 'app', 'closed_at', 'Closed at'],
            ['en-US', 'app', 'range', 'Range'],
            ['en-US', 'app', 'session_already_open', 'There is already an open session in this venue. Please close it before opening a new one.'],
            ['en-US', 'app', 'session_has_open_groups', 'Cannot close session. There are open billing groups in this session. Close or reassign them first.'],
            ['en-US', 'app', 'display_name', 'Display Name'],
            ['en-US', 'app', 'sort_order', 'Sort Order'],
            ['en-US', 'app', 'is_active', 'Active'],
            ['en-US', 'app', 'navigation_label_document_print_configs', 'Document Print Configs'],
            ['en-US', 'app', 'model_label_document_print_config', 'Document Print Config'],
            ['en-US', 'app', 'plural_model_label_document_print_configs', 'Document Print Configs'],
            ['en-US', 'app', 'helper_text_group_items', 'Group identical items and show quantity (e.g. "3x Pizza"). When off, each unit prints on its own line.'],
            ['en-US', 'app', 'helper_text_ignore_variants', 'Do not print variant names (e.g. "Casa", "Reserva") on this document type.'],
            ['en-US', 'app', 'helper_text_ignore_modifiers', 'Do not print modifier names (e.g. "without onion") on this document type.'],

            // ---------- auth ----------
            ['pt-PT', 'auth', 'sign_in', 'Iniciar sessão'],
            ['pt-PT', 'auth', 'password', 'Palavra-passe'],
            ['pt-PT', 'auth', 'username', 'Nome de utilizador'],
            ['pt-PT', 'auth', 'enter_password', 'Introduza a palavra-passe'],
            ['pt-PT', 'auth', 'enter_username', 'Introduza o nome de utilizador'],
            ['pt-PT', 'auth', 'user_menu', 'Menu do utilizador'],
            ['pt-PT', 'auth', 'admin_panel', 'Painel de administração'],
            ['pt-PT', 'auth', 'log_out', 'Terminar sessão'],
            ['pt-PT', 'auth', 'unauthorized', 'Não autorizado'],
            ['pt-PT', 'auth', 'no_valid_role', 'Nenhuma função válida atribuída'],

            ['en-US', 'auth', 'sign_in', 'Sign In'],
            ['en-US', 'auth', 'password', 'Password'],
            ['en-US', 'auth', 'username', 'Username'],
            ['en-US', 'auth', 'enter_password', 'Enter password'],
            ['en-US', 'auth', 'enter_username', 'Enter username'],
            ['en-US', 'auth', 'user_menu', 'User menu'],
            ['en-US', 'auth', 'admin_panel', 'Admin Panel'],
            ['en-US', 'auth', 'log_out', 'Log Out'],
            ['en-US', 'auth', 'unauthorized', 'Unauthorized'],
            ['en-US', 'auth', 'no_valid_role', 'No valid role assigned'],

            // ---------- floor ----------
            ['pt-PT', 'floor', 'title', 'Plano de sala'],
            ['pt-PT', 'floor', 'open_group', 'Abrir novo grupo'],
            ['pt-PT', 'floor', 'no_session', 'Não existe nenhuma sessão de serviço aberta. Crie uma sessão em Configuração → Sessões de serviço antes de operar o salão.'],
            ['pt-PT', 'floor', 'session_start', 'Início'],
            ['pt-PT', 'floor', 'open_groups', 'Contas abertas'],
            ['pt-PT', 'floor', 'no_open_groups', 'Nenhum grupo aberto nesta sessão.'],
            ['pt-PT', 'floor', 'no_zones', 'Sem zonas atribuídas'],
            ['pt-PT', 'floor', 'row', 'Fila'],
            ['pt-PT', 'floor', 'free', 'Livre'],
            ['pt-PT', 'floor', 'busy', 'Ocupado'],
            ['pt-PT', 'floor', 'tap_to_open', 'Toque para abrir grupo'],
            ['pt-PT', 'floor', 'no_sections', 'Nenhuma sala configurada.'],
            ['pt-PT', 'floor', 'selected_range', 'Intervalo selecionado'],
            ['pt-PT', 'floor', 'unauthorized', 'Não autorizado'],
            ['pt-PT', 'floor', 'filter_free_seats', 'Lugares livres'],
            ['pt-PT', 'floor', 'filter_active', 'Ativos'],
            ['pt-PT', 'floor', 'filter_favorites', 'Favoritos'],
            ['pt-PT', 'floor', 'favorite', 'Adicionar aos favoritos'],
            ['pt-PT', 'floor', 'unfavorite', 'Remover dos favoritos'],
            ['pt-PT', 'floor', 'auto_favorite', 'Auto-favoritado (servidor atribuído)'],
            ['pt-PT', 'floor', 'cannot_unfavorite_assigned', 'Não pode remover dos favoritos um grupo em que está atribuído.'],
            ['pt-PT', 'floor', 'number_of_seats', 'Número de Lugares'],
            ['pt-PT', 'floor', 'end_pair', 'Par Final'],
            ['pt-PT', 'floor', 'starting_pair', 'A partir de'],
            ['pt-PT', 'floor', 'zone_preview', 'Zona'],
            ['pt-PT', 'floor', 'pairs_count', ':count par|:count pares'],
            ['pt-PT', 'floor', 'invalid_end_pair', 'Identificação de par final inválida.'],
            ['pt-PT', 'floor', 'range_too_large', 'Apenas :max pares de lugares livres disponíveis a partir desta posição.'],
            ['pt-PT', 'floor', 'assigned_server_required', 'É obrigatório escolher o servidor atribuído.'],
            ['pt-PT', 'floor', 'assigned_server_invalid', 'O servidor atribuído tem de ser um utilizador ativo com a função SERVER.'],

            ['en-US', 'floor', 'title', 'Floor'],
            ['en-US', 'floor', 'open_group', 'Open Billing Group'],
            ['en-US', 'floor', 'no_session', 'No open service session. Create a session in Configuration → Service Sessions before operating the floor.'],
            ['en-US', 'floor', 'session_start', 'Start'],
            ['en-US', 'floor', 'open_groups', 'Open Billing Groups'],
            ['en-US', 'floor', 'no_open_groups', 'No open groups in this session.'],
            ['en-US', 'floor', 'no_zones', 'No zones assigned'],
            ['en-US', 'floor', 'row', 'Row'],
            ['en-US', 'floor', 'free', 'Free'],
            ['en-US', 'floor', 'busy', 'Busy'],
            ['en-US', 'floor', 'tap_to_open', 'Tap to open billing group'],
            ['en-US', 'floor', 'no_sections', 'No sections configured.'],
            ['en-US', 'floor', 'selected_range', 'Selected range'],
            ['en-US', 'floor', 'unauthorized', 'Unauthorized'],
            ['en-US', 'floor', 'filter_free_seats', 'Free Seats'],
            ['en-US', 'floor', 'filter_active', 'Active'],
            ['en-US', 'floor', 'filter_favorites', 'Favorites'],
            ['en-US', 'floor', 'favorite', 'Add to favorites'],
            ['en-US', 'floor', 'unfavorite', 'Remove from favorites'],
            ['en-US', 'floor', 'auto_favorite', 'Auto-favorited (assigned server)'],
            ['en-US', 'floor', 'cannot_unfavorite_assigned', 'Cannot unfavorite a group you are assigned to.'],
            ['en-US', 'floor', 'number_of_seats', 'Number of Seats'],
            ['en-US', 'floor', 'end_pair', 'End Pair'],
            ['en-US', 'floor', 'starting_pair', 'Starting from'],
            ['en-US', 'floor', 'zone_preview', 'Zone'],
            ['en-US', 'floor', 'pairs_count', ':count pair|:count pairs'],
            ['en-US', 'floor', 'invalid_end_pair', 'Invalid end pair label.'],
            ['en-US', 'floor', 'range_too_large', 'Only :max free seat pairs available from this position.'],
            ['en-US', 'floor', 'assigned_server_required', 'Assigned server is required.'],
            ['en-US', 'floor', 'assigned_server_invalid', 'Assigned server must be an active server user.'],

            // ---------- order ----------
            ['pt-PT', 'order', 'title', 'Pedido'],
            ['pt-PT', 'order', 'new_order', 'Novo pedido'],
            ['pt-PT', 'order', 'submit', 'Enviar pedido'],
            ['pt-PT', 'order', 'cart', 'Carrinho'],
            ['pt-PT', 'order', 'empty_cart', 'Nenhum item adicionado.'],
            ['pt-PT', 'order', 'remove', 'remover'],
            ['pt-PT', 'order', 'delivery_zone', 'Zona de entrega'],
            ['pt-PT', 'order', 'no_specific_zone', '— sem zona específica —'],
            ['pt-PT', 'order', 'seat_pair', 'Par de lugar (opcional)'],
            ['pt-PT', 'order', 'center_of_zone', '— centro da zona —'],
            ['pt-PT', 'order', 'order_notes', 'Notas'],
            ['pt-PT', 'order', 'cancel_back', 'Cancelar e voltar à conta'],
            ['pt-PT', 'order', 'order_sent', 'Pedido enviado para produção'],
            ['pt-PT', 'order', 'cart_empty_warning', 'Carrinho vazio'],
            ['pt-PT', 'order', 'order_failed', 'Falha ao submeter pedido'],
            ['pt-PT', 'order', 'group_level', 'Nível do grupo'],
            ['pt-PT', 'order', 'center', 'Centro'],
            ['pt-PT', 'order', 'order_entry', 'Novo pedido'],
            ['pt-PT', 'order', 'unauthorized', 'Não autorizado'],
            ['pt-PT', 'order', 'menu_tab', 'Menu'],
            ['pt-PT', 'order', 'order_tab', 'Pedido'],
            ['pt-PT', 'order', 'delivery', 'Entrega'],
            ['pt-PT', 'order', 'no_items', 'Sem items nesta categoria.'],

            ['en-US', 'order', 'title', 'Order'],
            ['en-US', 'order', 'new_order', 'New Order'],
            ['en-US', 'order', 'submit', 'Submit Order'],
            ['en-US', 'order', 'cart', 'Cart'],
            ['en-US', 'order', 'empty_cart', 'No items added.'],
            ['en-US', 'order', 'remove', 'remove'],
            ['en-US', 'order', 'delivery_zone', 'Delivery Zone'],
            ['en-US', 'order', 'no_specific_zone', '— no specific zone —'],
            ['en-US', 'order', 'seat_pair', 'Seat Pair (optional)'],
            ['en-US', 'order', 'center_of_zone', '— center of zone —'],
            ['en-US', 'order', 'order_notes', 'Notes'],
            ['en-US', 'order', 'cancel_back', 'Cancel and return to group'],
            ['en-US', 'order', 'order_sent', 'Order sent to production'],
            ['en-US', 'order', 'cart_empty_warning', 'Cart is empty'],
            ['en-US', 'order', 'order_failed', 'Failed to submit order'],
            ['en-US', 'order', 'group_level', 'Group level'],
            ['en-US', 'order', 'center', 'Center'],
            ['en-US', 'order', 'order_entry', 'Order Entry'],
            ['en-US', 'order', 'unauthorized', 'Unauthorized'],
            ['en-US', 'order', 'menu_tab', 'Menu'],
            ['en-US', 'order', 'order_tab', 'Order'],
            ['en-US', 'order', 'delivery', 'Delivery'],
            ['en-US', 'order', 'no_items', 'No items in this category.'],

            // ---------- billing ----------
            ['pt-PT', 'billing', 'group_title', 'Conta'],
            ['pt-PT', 'billing', 'name', 'Nome'],
            ['pt-PT', 'billing', 'name_placeholder', 'ex.: Família Silva'],
            ['pt-PT', 'billing', 'assign_zone', 'Atribuir zona'],
            ['pt-PT', 'billing', 'start_pair', 'Lugar inicial'],
            ['pt-PT', 'billing', 'end_pair', 'Lugar final'],
            ['pt-PT', 'billing', 'delivery_label', 'Etiqueta entrega'],
            ['pt-PT', 'billing', 'new_order', 'Novo pedido'],
            ['pt-PT', 'billing', 'print_bill', 'Imprimir conta'],
            ['pt-PT', 'billing', 'reopen_group', 'Reabrir conta'],
            ['pt-PT', 'billing', 'status', 'Estado'],
            ['pt-PT', 'billing', 'total_to_pay', 'Total a pagar'],
            ['pt-PT', 'billing', 'paid', 'Pago'],
            ['pt-PT', 'billing', 'open_balance', 'Saldo em aberto'],
            ['pt-PT', 'billing', 'occupied_zones', 'Zonas ocupadas'],
            ['pt-PT', 'billing', 'no_zones', 'Sem zonas atribuídas.'],
            ['pt-PT', 'billing', 'released', 'libertada'],
            ['pt-PT', 'billing', 'release_zone', 'Libertar'],
            ['pt-PT', 'billing', 'release_confirm', 'Libertar zona'],
            ['pt-PT', 'billing', 'orders', 'Pedidos'],
            ['pt-PT', 'billing', 'no_orders', 'Sem pedidos.'],
            ['pt-PT', 'billing', 'item', 'Item'],
            ['pt-PT', 'billing', 'qty', 'Qtd'],
            ['pt-PT', 'billing', 'route', 'Rota'],
            ['pt-PT', 'billing', 'delivery', 'Entrega'],
            ['pt-PT', 'billing', 'subtotal', 'Subtotal'],
            ['pt-PT', 'billing', 'documents_payments', 'Documentos & pagamentos'],
            ['pt-PT', 'billing', 'printed_bills', 'Contas impressas'],
            ['pt-PT', 'billing', 'no_bills', 'Sem contas impressas.'],
            ['pt-PT', 'billing', 'reprint', 'reimpressão'],
            ['pt-PT', 'billing', 'payments', 'Pagamentos'],
            ['pt-PT', 'billing', 'no_payments', 'Sem pagamentos.'],
            ['pt-PT', 'billing', 'zone_assigned', 'Zona atribuída'],
            ['pt-PT', 'billing', 'zone_overlap', 'Sobreposição de zonas'],
            ['pt-PT', 'billing', 'zone_error', 'Erro ao atribuir zona'],
            ['pt-PT', 'billing', 'zone_released', 'Zona libertada'],
            ['pt-PT', 'billing', 'bill_sent', 'Conta enviada para impressão'],
            ['pt-PT', 'billing', 'group_reopened', 'Conta reaberta'],
            ['pt-PT', 'billing', 'closed_group', 'Conta fechada.'],
            ['pt-PT', 'billing', 'bill_error', 'Erro'],
            ['pt-PT', 'billing', 'checkout', 'Caixa'],
            ['pt-PT', 'billing', 'charges', 'Consumo'],
            ['pt-PT', 'billing', 'voided', 'Anulado'],
            ['pt-PT', 'billing', 'add_order', 'Adicionar pedido'],
            ['pt-PT', 'billing', 'add_zone', 'Adicionar zona'],
            ['pt-PT', 'billing', 'no_bills_found', 'Nenhuma conta encontrada.'],
            ['pt-PT', 'billing', 'select_row', 'Selecione fila'],
            ['pt-PT', 'billing', 'reopen_error', 'Erro ao reabrir conta'],
            ['pt-PT', 'billing', 'zone_release_unauthorized', 'Não autorizado a libertar zona'],
            ['pt-PT', 'billing', 'zone_release_error', 'Erro ao libertar zona'],

            ['en-US', 'billing', 'group_title', 'Group'],
            ['en-US', 'billing', 'name', 'Name'],
            ['en-US', 'billing', 'name_placeholder', 'e.g. Smith Family'],
            ['en-US', 'billing', 'assign_zone', 'Assign Zone'],
            ['en-US', 'billing', 'start_pair', 'Start Pair'],
            ['en-US', 'billing', 'end_pair', 'End Pair'],
            ['en-US', 'billing', 'delivery_label', 'Delivery Label'],
            ['en-US', 'billing', 'new_order', 'New Order'],
            ['en-US', 'billing', 'print_bill', 'Print Bill'],
            ['en-US', 'billing', 'reopen_group', 'Reopen Group'],
            ['en-US', 'billing', 'status', 'Status'],
            ['en-US', 'billing', 'total_to_pay', 'Total to Pay'],
            ['en-US', 'billing', 'paid', 'Paid'],
            ['en-US', 'billing', 'open_balance', 'Open Balance'],
            ['en-US', 'billing', 'occupied_zones', 'Occupied Zones'],
            ['en-US', 'billing', 'no_zones', 'No zones assigned.'],
            ['en-US', 'billing', 'released', 'released'],
            ['en-US', 'billing', 'release_zone', 'Release'],
            ['en-US', 'billing', 'release_confirm', 'Release zone'],
            ['en-US', 'billing', 'orders', 'Orders'],
            ['en-US', 'billing', 'no_orders', 'No orders yet.'],
            ['en-US', 'billing', 'item', 'Item'],
            ['en-US', 'billing', 'qty', 'Qty'],
            ['en-US', 'billing', 'route', 'Route'],
            ['en-US', 'billing', 'delivery', 'Delivery'],
            ['en-US', 'billing', 'subtotal', 'Subtotal'],
            ['en-US', 'billing', 'documents_payments', 'Documents & Payments'],
            ['en-US', 'billing', 'printed_bills', 'Printed Bills'],
            ['en-US', 'billing', 'no_bills', 'No bills printed.'],
            ['en-US', 'billing', 'reprint', 'reprint'],
            ['en-US', 'billing', 'payments', 'Payments'],
            ['en-US', 'billing', 'no_payments', 'No payments.'],
            ['en-US', 'billing', 'zone_assigned', 'Zone assigned'],
            ['en-US', 'billing', 'zone_overlap', 'Zone overlap'],
            ['en-US', 'billing', 'zone_error', 'Error assigning zone'],
            ['en-US', 'billing', 'zone_released', 'Zone released'],
            ['en-US', 'billing', 'bill_sent', 'Bill sent to printer'],
            ['en-US', 'billing', 'group_reopened', 'Group reopened'],
            ['en-US', 'billing', 'closed_group', 'Group is closed.'],
            ['en-US', 'billing', 'bill_error', 'Error'],
            ['en-US', 'billing', 'checkout', 'Checkout'],
            ['en-US', 'billing', 'charges', 'Charges'],
            ['en-US', 'billing', 'voided', 'Voided'],
            ['en-US', 'billing', 'add_order', 'Add Order'],
            ['en-US', 'billing', 'add_zone', 'Add Zone'],
            ['en-US', 'billing', 'no_bills_found', 'No bills found.'],
            ['en-US', 'billing', 'select_row', 'Select row'],
            ['en-US', 'billing', 'reopen_error', 'Failed to reopen group'],
            ['en-US', 'billing', 'zone_release_unauthorized', 'Unauthorized to release zone'],
            ['en-US', 'billing', 'zone_release_error', 'Failed to release zone'],

            // ---------- cashier ----------
            ['pt-PT', 'cashier', 'title', 'Contas'],
            ['pt-PT', 'cashier', 'no_session', 'Não existe sessão de serviço aberta.'],
            ['pt-PT', 'cashier', 'no_groups', 'Nenhum grupo a apresentar.'],
            ['pt-PT', 'cashier', 'group', 'Conta'],
            ['pt-PT', 'cashier', 'zones', 'Zonas'],
            ['pt-PT', 'cashier', 'total', 'Total'],
            ['pt-PT', 'cashier', 'paid', 'Pago'],
            ['pt-PT', 'cashier', 'balance', 'Saldo'],
            ['pt-PT', 'cashier', 'actions', 'Ações'],
            ['pt-PT', 'cashier', 'print_bill', 'Imprimir conta'],
            ['pt-PT', 'cashier', 'reprint', 'Reimprimir'],
            ['pt-PT', 'cashier', 'reopen', 'Reabrir'],
            ['pt-PT', 'cashier', 'reopen_confirm', 'Reabrir conta'],
            ['pt-PT', 'cashier', 'record_payment', 'Registar pagamento'],
            ['pt-PT', 'cashier', 'payment_group', 'Conta'],
            ['pt-PT', 'cashier', 'payment_amount', 'Valor (€)'],
            ['pt-PT', 'cashier', 'payment_label', 'Forma de pagamento'],
            ['pt-PT', 'cashier', 'payment_default', 'Numerário'],
            ['pt-PT', 'cashier', 'payment_recorded', 'Pagamento registado'],
            ['pt-PT', 'cashier', 'show_closed', 'Mostrar fechados'],
            ['pt-PT', 'cashier', 'hide_closed', 'Ocultar fechados'],
            ['pt-PT', 'cashier', 'bill_sent', 'Conta enviada para impressora'],
            ['pt-PT', 'cashier', 'no_bill_reprint', 'Sem conta para reimprimir'],
            ['pt-PT', 'cashier', 'reprint_sent', 'Reimpressão enviada'],
            ['pt-PT', 'cashier', 'billing_groups', 'Contas'],
            ['pt-PT', 'cashier', 'search_placeholder', 'Pesquise por nome, código ou sala...'],
            ['pt-PT', 'cashier', 'no_groups_found', 'Nenhuma conta encontrada.'],
            ['pt-PT', 'cashier', 'amount', 'Valor'],
            ['pt-PT', 'cashier', 'fill_balance', 'Preencher saldo'],
            ['pt-PT', 'cashier', 'payment_method', 'Método de pagamento'],
            ['pt-PT', 'cashier', 'production_tickets', 'Tickets de produção'],
            ['pt-PT', 'cashier', 'items', 'itens'],
            ['pt-PT', 'cashier', 'no_tickets_found', 'Nenhum ticket encontrado.'],
            ['pt-PT', 'cashier', 'no_bills_found', 'Nenhuma conta encontrada.'],
            ['pt-PT', 'cashier', 'select_group_docs', 'Selecione uma conta para ver documentos imprimíveis.'],
            ['pt-PT', 'cashier', 'open_group_for_reprint', 'Abra uma conta a partir da pesquisa para aceder a reimpressões.'],
            ['pt-PT', 'cashier', 'reprint_documents', 'Reimpressão e documentos'],
            ['pt-PT', 'cashier', 'unauthorized', 'Não autorizado'],
            ['pt-PT', 'cashier', 'last_updated', 'Última atualização'],
            ['pt-PT', 'cashier', 'refresh', 'Atualizar'],

            ['en-US', 'cashier', 'title', 'Checkout'],
            ['en-US', 'cashier', 'no_session', 'No open service session.'],
            ['en-US', 'cashier', 'no_groups', 'No groups to display.'],
            ['en-US', 'cashier', 'group', 'Group'],
            ['en-US', 'cashier', 'zones', 'Zones'],
            ['en-US', 'cashier', 'total', 'Total'],
            ['en-US', 'cashier', 'paid', 'Paid'],
            ['en-US', 'cashier', 'balance', 'Balance'],
            ['en-US', 'cashier', 'actions', 'Actions'],
            ['en-US', 'cashier', 'print_bill', 'Print Bill'],
            ['en-US', 'cashier', 'reprint', 'Reprint'],
            ['en-US', 'cashier', 'reopen', 'Reopen'],
            ['en-US', 'cashier', 'reopen_confirm', 'Reopen group'],
            ['en-US', 'cashier', 'record_payment', 'Record Payment'],
            ['en-US', 'cashier', 'payment_group', 'Group'],
            ['en-US', 'cashier', 'payment_amount', 'Amount (€)'],
            ['en-US', 'cashier', 'payment_label', 'Payment Method'],
            ['en-US', 'cashier', 'payment_default', 'Cash'],
            ['en-US', 'cashier', 'payment_recorded', 'Payment recorded'],
            ['en-US', 'cashier', 'show_closed', 'Show closed'],
            ['en-US', 'cashier', 'hide_closed', 'Hide closed'],
            ['en-US', 'cashier', 'bill_sent', 'Bill sent to printer'],
            ['en-US', 'cashier', 'no_bill_reprint', 'No bill to reprint'],
            ['en-US', 'cashier', 'reprint_sent', 'Reprint sent'],
            ['en-US', 'cashier', 'billing_groups', 'Billing Groups'],
            ['en-US', 'cashier', 'search_placeholder', 'Search by name, code or section...'],
            ['en-US', 'cashier', 'no_groups_found', 'No billing groups found.'],
            ['en-US', 'cashier', 'amount', 'Amount'],
            ['en-US', 'cashier', 'fill_balance', 'Fill balance'],
            ['en-US', 'cashier', 'payment_method', 'Payment Method'],
            ['en-US', 'cashier', 'production_tickets', 'Production Tickets'],
            ['en-US', 'cashier', 'items', 'items'],
            ['en-US', 'cashier', 'no_tickets_found', 'No tickets found.'],
            ['en-US', 'cashier', 'no_bills_found', 'No bills found.'],
            ['en-US', 'cashier', 'select_group_docs', 'Select a billing group to view printable documents.'],
            ['en-US', 'cashier', 'open_group_for_reprint', 'Open a billing group from lookup to access reprint options.'],
            ['en-US', 'cashier', 'reprint_documents', 'Reprint & Documents'],
            ['en-US', 'cashier', 'unauthorized', 'Unauthorized'],
            ['en-US', 'cashier', 'last_updated', 'Last updated'],
            ['en-US', 'cashier', 'refresh', 'Refresh'],

            // ---------- dashboard ----------
            ['pt-PT', 'dashboard', 'title', 'Painel principal'],
            ['pt-PT', 'dashboard', 'floor_tile', 'Plano de sala'],
            ['pt-PT', 'dashboard', 'floor_description', 'Ver ocupação e gerir lugares'],
            ['pt-PT', 'dashboard', 'lookup_tile', 'Contas'],
            ['pt-PT', 'dashboard', 'lookup_description', 'Pesquisar e gerir contas'],
            ['pt-PT', 'dashboard', 'reprint_tile', 'Reimpressão'],
            ['pt-PT', 'dashboard', 'reprint_description', 'Reimprimir contas e documentos'],
            ['pt-PT', 'dashboard', 'admin_panel_tile', 'Painel de administração'],
            ['pt-PT', 'dashboard', 'admin_panel_description', 'Configuração e definições do sistema'],
            ['pt-PT', 'dashboard', 'active_session', 'Sessão ativa'],
            ['pt-PT', 'dashboard', 'no_session', 'Não existe sessão de serviço aberta'],
            ['pt-PT', 'dashboard', 'no_session_help', 'Abra uma sessão de serviço em Configuração → Sessões de serviço antes de fazer pedidos, gerar contas ou registar pagamentos.'],

            ['en-US', 'dashboard', 'title', 'Dashboard'],
            ['en-US', 'dashboard', 'floor_tile', 'Floor'],
            ['en-US', 'dashboard', 'floor_description', 'View occupancy and manage seating'],
            ['en-US', 'dashboard', 'lookup_tile', 'Billing Groups'],
            ['en-US', 'dashboard', 'lookup_description', 'Search and manage billing groups'],
            ['en-US', 'dashboard', 'reprint_tile', 'Reprint'],
            ['en-US', 'dashboard', 'reprint_description', 'Reprint bills and documents'],
            ['en-US', 'dashboard', 'admin_panel_tile', 'Admin Panel'],
            ['en-US', 'dashboard', 'admin_panel_description', 'Configuration and system settings'],
            ['en-US', 'dashboard', 'active_session', 'Active session'],
            ['en-US', 'dashboard', 'no_session', 'No open service session'],
            ['en-US', 'dashboard', 'no_session_help', 'Open a service session in Configuration → Service Sessions before placing orders, generating bills, or recording payments.'],

            // ---------- ticket ----------
            ['pt-PT', 'ticket', 'void', 'ANULAÇÃO'],
            ['pt-PT', 'ticket', 'reprint', 'REIMPRESSÃO'],
            ['pt-PT', 'ticket', 'group', 'Conta'],
            ['pt-PT', 'ticket', 'zone', 'Zona'],
            ['pt-PT', 'ticket', 'delivery', 'Entrega'],
            ['pt-PT', 'ticket', 'time', 'Hora'],
            ['pt-PT', 'ticket', 'ticket_num', 'Ticket'],
            ['pt-PT', 'ticket', 'internal_bill', 'CONTA'],
            ['pt-PT', 'ticket', 'document', 'Documento'],
            ['pt-PT', 'ticket', 'subtotal', 'SUBTOTAL'],
            ['pt-PT', 'ticket', 'total', 'TOTAL'],
            ['pt-PT', 'ticket', 'paid', 'Pago'],
            ['pt-PT', 'ticket', 'due', 'Em dívida'],
            ['pt-PT', 'ticket', 'no_fiscal', 'Documento interno - sem valor fiscal'],
            ['pt-PT', 'ticket', 'currency', '€'],
            ['pt-PT', 'ticket', 'name', 'Nome'],
            ['pt-PT', 'ticket', 'zones', 'Zonas'],
            ['pt-PT', 'ticket', 'server', 'Servidor'],
            ['pt-PT', 'ticket', 'assigned', 'Atribuídos'],
            ['pt-PT', 'ticket', 'order_num', 'Pedido'],
            ['pt-PT', 'ticket', 'notes', 'Notas'],
            ['pt-PT', 'ticket', 'unknown_item', 'Item #:id'],
            ['pt-PT', 'ticket', 'delivery_arrow', '   -> :label'],

            ['en-US', 'ticket', 'void', 'VOID'],
            ['en-US', 'ticket', 'reprint', 'REPRINT'],
            ['en-US', 'ticket', 'group', 'Group'],
            ['en-US', 'ticket', 'zone', 'Zone'],
            ['en-US', 'ticket', 'delivery', 'Delivery'],
            ['en-US', 'ticket', 'time', 'Time'],
            ['en-US', 'ticket', 'ticket_num', 'Ticket'],
            ['en-US', 'ticket', 'internal_bill', 'INTERNAL BILL'],
            ['en-US', 'ticket', 'document', 'Document'],
            ['en-US', 'ticket', 'subtotal', 'SUBTOTAL'],
            ['en-US', 'ticket', 'total', 'TOTAL'],
            ['en-US', 'ticket', 'paid', 'Paid'],
            ['en-US', 'ticket', 'due', 'Due'],
            ['en-US', 'ticket', 'no_fiscal', 'Internal document - no fiscal value'],
            ['en-US', 'ticket', 'currency', '€'],
            ['en-US', 'ticket', 'name', 'Name'],
            ['en-US', 'ticket', 'zones', 'Zones'],
            ['en-US', 'ticket', 'server', 'Server'],
            ['en-US', 'ticket', 'assigned', 'Assigned'],
            ['en-US', 'ticket', 'order_num', 'Order'],
            ['en-US', 'ticket', 'notes', 'Notes'],
            ['en-US', 'ticket', 'unknown_item', 'Item #:id'],
            ['en-US', 'ticket', 'delivery_arrow', '   -> :label'],

            // ---------- app (modifier sets & variants) ----------
            ['pt-PT', 'app', 'navigation_label_modifier_sets', 'Conjuntos de modificadores'],
            ['pt-PT', 'app', 'model_label_modifier_set', 'Conjunto de modificadores'],
            ['pt-PT', 'app', 'plural_model_label_modifier_sets', 'Conjuntos de modificadores'],
            ['pt-PT', 'app', 'modifier_set', 'Conjunto de modificadores'],
            ['pt-PT', 'app', 'add_modifier_item', 'Adicionar modificador'],
            ['pt-PT', 'app', 'add_variant', 'Adicionar variante'],
            ['pt-PT', 'app', 'modifier_selection_single', 'Única'],
            ['pt-PT', 'app', 'modifier_selection_multiple', 'Múltipla'],
            ['pt-PT', 'app', 'assume_default', 'Assumir pré-definição'],
            ['pt-PT', 'app', 'assume_default_help', 'Quando ativado, os servidores não precisam escolher um modificador — o pré-definido é selecionado automaticamente.'],
            ['pt-PT', 'app', 'is_default', 'Modificador pré-definido'],
            ['pt-PT', 'app', 'is_default_help', 'Quando o conjunto assume a pré-definição, este modificador é selecionado automaticamente para os servidores.'],
            ['pt-PT', 'app', 'default_modifier_item', 'Modificador pré-definido'],
            ['pt-PT', 'app', 'none', 'Nenhum'],
            ['pt-PT', 'app', 'items', 'Itens'],
            ['pt-PT', 'app', 'health_check_run', 'Verificar saúde'],
            ['pt-PT', 'app', 'health_check_complete', 'Verificação de saúde concluída'],
            ['pt-PT', 'app', 'test_print', 'Teste de impressão'],
            ['pt-PT', 'app', 'test_print_sent', 'Teste de impressão enviado com sucesso'],
            ['pt-PT', 'app', 'test_print_failed', 'Teste de impressão falhou'],
            ['pt-PT', 'app', 'cashier_printer', 'Impressora de contas'],
            ['pt-PT', 'app', 'cashier_printer_help', 'Impressora usada para imprimir contas de clientes'],
            ['pt-PT', 'app', 'print_config_section', 'Configuração de impressão'],
            ['pt-PT', 'app', 'print_char_width', 'Caracteres por linha'],
            ['pt-PT', 'app', 'print_char_width_help', 'Largura do conteúdo do ticket em caracteres (20–64, padrão 48)'],
            ['pt-PT', 'app', 'print_begin_space', 'Linhas de avanço inicial'],
            ['pt-PT', 'app', 'print_begin_space_help', 'Linhas em branco antes do conteúdo (0–10, padrão 0)'],
            ['pt-PT', 'app', 'print_end_space', 'Linhas de avanço final'],
            ['pt-PT', 'app', 'print_end_space_help', 'Linhas em branco após o conteúdo, antes do corte (0–10, padrão 3)'],
            ['pt-PT', 'app', 'retry_selected', 'Reenviar selecionados'],
            ['pt-PT', 'app', 'retry_batch_result', ':success reenviado(s), :skipped ignorado(s)'],
            ['pt-PT', 'app', 'retry_batch_success', 'Reenviado(s)'],
            ['pt-PT', 'app', 'retry_batch_none', 'Nenhum reenviado'],

            ['en-US', 'app', 'navigation_label_modifier_sets', 'Modifier Sets'],
            ['en-US', 'app', 'model_label_modifier_set', 'Modifier Set'],
            ['en-US', 'app', 'plural_model_label_modifier_sets', 'Modifier Sets'],
            ['en-US', 'app', 'modifier_set', 'Modifier Set'],
            ['en-US', 'app', 'add_modifier_item', 'Add Modifier'],
            ['en-US', 'app', 'add_variant', 'Add Variant'],
            ['en-US', 'app', 'modifier_selection_single', 'Single'],
            ['en-US', 'app', 'modifier_selection_multiple', 'Multiple'],
            ['en-US', 'app', 'assume_default', 'Assume Default'],
            ['en-US', 'app', 'assume_default_help', 'When enabled, servers will not need to pick a modifier — the default will be pre-selected automatically.'],
            ['en-US', 'app', 'is_default', 'Default Modifier'],
            ['en-US', 'app', 'is_default_help', 'When the set assumes default, this modifier is pre-selected automatically for servers.'],
            ['en-US', 'app', 'default_modifier_item', 'Default Modifier'],
            ['en-US', 'app', 'none', 'None'],
            ['en-US', 'app', 'items', 'Items'],
            ['en-US', 'app', 'health_check_run', 'Run Health Check'],
            ['en-US', 'app', 'health_check_complete', 'Health check complete'],
            ['en-US', 'app', 'test_print', 'Test Print'],
            ['en-US', 'app', 'test_print_sent', 'Test print sent successfully'],
            ['en-US', 'app', 'test_print_failed', 'Test print failed'],
            ['en-US', 'app', 'cashier_printer', 'Bill Printer'],
            ['en-US', 'app', 'cashier_printer_help', 'Printer used to print customer bills'],
            ['en-US', 'app', 'print_config_section', 'Print Configuration'],
            ['en-US', 'app', 'print_char_width', 'Characters per line'],
            ['en-US', 'app', 'print_char_width_help', 'Ticket content width in characters (20–64, default 48)'],
            ['en-US', 'app', 'print_begin_space', 'Begin feed lines'],
            ['en-US', 'app', 'print_begin_space_help', 'Blank lines fed before content (0–10, default 0)'],
            ['en-US', 'app', 'print_end_space', 'End feed lines'],
            ['en-US', 'app', 'print_end_space_help', 'Blank lines fed after content, before cut (0–10, default 3)'],
            ['en-US', 'app', 'retry_selected', 'Retry selected'],
            ['en-US', 'app', 'retry_batch_result', ':success retried, :skipped skipped'],
            ['en-US', 'app', 'retry_batch_success', 'Retried'],
            ['en-US', 'app', 'retry_batch_none', 'Nothing retried'],

            // ---------- menu ----------
            ['pt-PT', 'menu', 'title', 'Menu'],
            ['pt-PT', 'menu', 'subtitle', 'Consultar o catálogo completo de items disponíveis.'],
            ['pt-PT', 'menu', 'no_categories', 'Sem categorias de menu disponíveis.'],
            ['pt-PT', 'menu', 'no_items', 'Sem items nesta categoria.'],
            ['pt-PT', 'menu', 'variants', 'Variantes'],
            ['pt-PT', 'menu', 'modifiers', 'Modificadores'],
            ['pt-PT', 'menu', 'default', 'padrão'],
            ['pt-PT', 'menu', 'route_kitchen', 'Cozinha'],
            ['pt-PT', 'menu', 'route_bar', 'Bar'],

            ['en-US', 'menu', 'title', 'Menu'],
            ['en-US', 'menu', 'subtitle', 'Browse the full catalog of available items.'],
            ['en-US', 'menu', 'no_categories', 'No menu categories available.'],
            ['en-US', 'menu', 'no_items', 'No items in this category.'],
            ['en-US', 'menu', 'variants', 'Variants'],
            ['en-US', 'menu', 'modifiers', 'Modifiers'],
            ['en-US', 'menu', 'default', 'default'],
            ['en-US', 'menu', 'route_kitchen', 'Kitchen'],
            ['en-US', 'menu', 'route_bar', 'Bar'],

            // ---------- order (variants & modifiers) ----------
            ['pt-PT', 'order', 'select_variant', 'Selecionar variante'],
            ['pt-PT', 'order', 'no_modifier', 'Nenhum'],
            ['pt-PT', 'order', 'add_to_order', 'Adicionar'],
            ['pt-PT', 'order', 'has_variants', 'Variantes'],
            ['pt-PT', 'order', 'has_modifiers', 'Modificadores'],
            ['pt-PT', 'order', 'has_variants_and_modifiers', 'Variantes e modificadores'],

            ['en-US', 'order', 'select_variant', 'Select variant'],
            ['en-US', 'order', 'no_modifier', 'None'],
            ['en-US', 'order', 'add_to_order', 'Add to order'],
            ['en-US', 'order', 'has_variants', 'Variants'],
            ['en-US', 'order', 'has_modifiers', 'Modifiers'],
            ['en-US', 'order', 'has_variants_and_modifiers', 'Variants & Modifiers'],
            ['en-US', 'order', 'unspecified', 'Unspecified'],

            ['pt-PT', 'order', 'unspecified', 'Ignorar'],
        ];
        foreach ($translations as [$lang, $ns, $key, $val]) {
            TranslationKey::updateOrCreate(
                ['language_code' => $lang, 'translation_namespace' => $ns, 'translation_key' => $key],
                ['translation_value' => $val, 'is_active' => true]
            );
        }

        // Record that seeding completed at this version
        Setting::setValue('core_seed_version', self::SEED_VERSION);
    }
}
